spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpatest
    username: sa
    password:
    driver-class-name: org.h2.Driver
    # initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
resources:
  location: /tmp/image/
  uri-path: /image