INSERT INTO SEQ_MASTER (SEQ_ID, SEQ_NAME, SEQ_LEN) VALUES ('orderNum', '주문번호', 5);
INSERT INTO SEQ_MASTER (SEQ_ID, SEQ_NAME, SEQ_LEN) VALUES ('deliveryId', '배송아이디', 4);
INSERT INTO SEQ_MASTER (SEQ_ID, SEQ_NAME, SEQ_LEN) VALUES ('prodCd', '상품 아이디', 7);

INSERT INTO SEQ_DETAIL (SEQ_ID, SEQ_KEY, NUM) VALUES ('prodCd', 'prodCd', 2);